function(GetFileBaseName input output exe_length)
    set(input_length ${ARGN})
    if(NOT input_length)
        string(LENGTH "${input}" input_length)
    endif()
    math(EXPR new_length "${input_length} - ${exe_length}")
    string(SUBSTRING "${input}" 0 ${new_length} ${output})
    set(${output} "${${output}}" PARENT_SCOPE)
endfunction()